%%{ init: { 'flowchart': { 'curve': 'linear' } } }%%
graph LR;

    Entrada1["Entrada 1"]
    Entrada2["Entrada 2"]
    Entrada3["Entrada 3"]


    SISTEMA["
    <br>
    ____________________<br>
    Sistema
    ____________________<br>
    <br><br>"]

    Saída1["Saída 1"]
    Saída2["Saída 2"]
    Saída3["Saída 3"]

    Entrada1:::white --> SISTEMA:::black --> Saída1:::white
    Entrada2:::white --> SISTEMA:::black --> Saída2:::white
    Entrada3:::white --> SISTEMA:::black --> Saída3:::white

    classDef white fill:#FFFFFF, color:#000000, stroke:#000000
    classDef black fill:orange, color:#FFFFFF, stroke:#000000

