%%{ init: { 'flowchart': { 'curve': 'linear' } } }%%
graph LR;

    Entrada1["<i>u<sub>1</sub>(t)</i>"]
    Entrada2["<i>u<sub>2</sub>(t)</i>"]
    Entrada3["<i>u<sub>1</sub>(t) + u<sub>2</sub>(t)</i>"]


    SISTEMA1["
    <i>𝜋̈ (t) + &beta; &middot; 𝜋 (t) = u(t)</i>
    "]  

    SISTEMA2["
    <i>𝜋̈ (t) + &beta; &middot; 𝜋 (t) = u(t)</i>
    "]  

    SISTEMA3["
    <i>𝜋̈ (t) + &beta; &middot; 𝜋 (t) = u(t)</i>
    "]    
    Saída1["<i>𝜋<sub>1</sub>(t)</i>"]
    Saída2["<i>𝜋<sub>2</sub>(t)</i>"]
    Saída3["<i>𝜋<sub>1</sub>(t) + 𝜋<sub>2</sub>(t)</i>"]

    Entrada1:::white --> SISTEMA1:::black --> Saída1:::white

    Entrada2:::white --> SISTEMA2:::black --> Saída2:::white

    Entrada3:::white --> SISTEMA3:::black --> Saída3:::white

    classDef white fill:#FFFFFF, color:#000000, stroke:#000000
    classDef black fill:white, color:black, stroke:#000000

